"""Subclass of FrameGrafik, which is generated by wxFormBuilder."""

import wx

import hexaco.views.maingui


# Implementing FrameGrafik
class hexacoFrameGrafik(views.maingui.FrameGrafik):

	def __init__(self, parent):
		views.maingui.FrameGrafik.__init__(self, parent)

		sizer = wx.BoxSizer(wx.HORIZONTAL)
		self.panel1 = wx.Panel(self)
		
		self.panel1.SetBackgroundColour(wx.Colour(133, 300, 300))
		sizer.Add(self.panel1, 1, wx.ALL | wx.EXPAND)
		self.SetSizer(sizer)


if __name__ == "__main__":
	root = wx.App()
	App = hexacoFrameGrafik(None)
	App.Show()
	root.MainLoop()
