

Sincerity = {"L":[{"Nilai Median":"3.17"},
                {"Nilai Tinggi" :"Kecenderungan untuk tulus dalam hubungan interpersonal.  Orang dengan skor tinggi tidak mau memanipulasi orang lain."},
                {"Nilai Rendah" :"Kecenderungan untuk tulus dalam hubungan interpersonal. Orang dengan skor rendah akan menyanjung orang lain atau pura-pura menyukai mereka demi mendapatkan bantuan."},
                {"Prilaku Tinggi":"-Tulus dalam bekerja\n-Enggan mencurangi orang lain demi kepentiangan pribadi\n-Kooperatif"},
                {"Prilaku Rendah":"-Bekerja dengan baik apabila ada imbalan\n-Akan melakukan apa saja untuk mencapai apa yang diharapkan\n-sulit diajak bekerjasama"}],
             "P":[{"Nilai Median":"3.31"},
                {"Nilai Tinggi" :""},
                {"Nilai Rendah" :""},
                {"Prilaku Tinggi":""},
                {"Prilaku Rendah":""}]}

Fairness = {"L":[{"Nilai Median":"3.33"},
                {"Nilai Tinggi" :""},
                {"Nilai Rendah" :""},
                {"Prilaku Tinggi":""},
                {"Prilaku Rendah":""}],
             "P":[{"Nilai Median":"3.73"},
                {"Nilai Tinggi" :""},
                {"Nilai Rendah" :""},
                {"Prilaku Tinggi":""},
                {"Prilaku Rendah":""}]}
            
Greed_Avoidance = {"L":[{"Nilai Median":"2.88"},
                {"Nilai Tinggi" :""},
                {"Nilai Rendah" :""},
                {"Prilaku Tinggi":""},
                {"Prilaku Rendah":""}],
             "P":[{"Nilai Median":"3.22"},
                {"Nilai Tinggi" :""},
                {"Nilai Rendah" :""},
                {"Prilaku Tinggi":""},
                {"Prilaku Rendah":""}]}

Modesty = {"L":[{"Nilai Median":"3.22"},
                {"Nilai Tinggi" :""},
                {"Nilai Rendah" :""},
                {"Prilaku Tinggi":""},
                {"Prilaku Rendah":""}],
             "P":[{"Nilai Median":"3.63"},
                {"Nilai Tinggi" :""},
                {"Nilai Rendah" :""},
                {"Prilaku Tinggi":""},
                {"Prilaku Rendah":""}]}

Honesty_Humility = {"L":[{"Nilai Median":"3.15"},
                        {"Nilai Tinggi" :""},
                        {"Nilai Rendah" :""},
                        {"Prilaku Tinggi":""},
                        {"Prilaku Rendah":""}],
                     "P":[{"Nilai Median":"3.45"},
                        {"Nilai Tinggi" :""},
                        {"Nilai Rendah" :""},
                        {"Prilaku Tinggi":""},
                        {"Prilaku Rendah":""}]}

Fearfulness = {"L":[{"Nilai Median":"2.52"},
                    {"Nilai Tinggi" :""},
                    {"Nilai Rendah" :""},
                    {"Prilaku Tinggi":""},
                    {"Prilaku Rendah":""}],
                 "P":[{"Nilai Median":"3.12"},
                    {"Nilai Tinggi" :""},
                    {"Nilai Rendah" :""},
                    {"Prilaku Tinggi":""},
                    {"Prilaku Rendah":""}]}

Anxiety = {"L":[{"Nilai Median":"3.32"},
                {"Nilai Tinggi" :""},
                {"Nilai Rendah" :""},
                {"Prilaku Tinggi":""},
                {"Prilaku Rendah":""}],
             "P":[{"Nilai Median":"3.76"},
                {"Nilai Tinggi" :""},
                {"Nilai Rendah" :""},
                {"Prilaku Tinggi":""},
                {"Prilaku Rendah":""}]}

Dependence = {"L":[{"Nilai Median":"2.61"},
                {"Nilai Tinggi" :""},
                {"Nilai Rendah" :""},
                {"Prilaku Tinggi":""},
                {"Prilaku Rendah":""}],
             "P":[{"Nilai Median":"3.08"},
                {"Nilai Tinggi" :""},
                {"Nilai Rendah" :""},
                {"Prilaku Tinggi":""},
                {"Prilaku Rendah":""}]}

Sentimentality = {"L":[{"Nilai Median":""},
        {"Nilai Tinggi" :""},
        {"Nilai Rendah" :""},
        {"Prilaku Tinggi":""},
        {"Prilaku Rendah":""}],
     "P":[{"Nilai Median":"3.10"},
        {"Nilai Tinggi" :""},
        {"Nilai Rendah" :""},
        {"Prilaku Tinggi":""},
        {"Prilaku Rendah":""}]}

Emotionality = {"L":[{"Nilai Median":""},
        {"Nilai Tinggi" :""},
        {"Nilai Rendah" :""},
        {"Prilaku Tinggi":""},
        {"Prilaku Rendah":""}],
     "P":[{"Nilai Median":"3.10"},
        {"Nilai Tinggi" :""},
        {"Nilai Rendah" :""},
        {"Prilaku Tinggi":""},
        {"Prilaku Rendah":""}]}

Social_self_esteem = {"L":[{"Nilai Median":""},
        {"Nilai Tinggi" :""},
        {"Nilai Rendah" :""},
        {"Prilaku Tinggi":""},
        {"Prilaku Rendah":""}],
     "P":[{"Nilai Median":"3.10"},
        {"Nilai Tinggi" :""},
        {"Nilai Rendah" :""},
        {"Prilaku Tinggi":""},
        {"Prilaku Rendah":""}]}

Social_boldness = {"L":[{"Nilai Median":""},
        {"Nilai Tinggi" :""},
        {"Nilai Rendah" :""},
        {"Prilaku Tinggi":""},
        {"Prilaku Rendah":""}],
     "P":[{"Nilai Median":"3.10"},
        {"Nilai Tinggi" :""},
        {"Nilai Rendah" :""},
        {"Prilaku Tinggi":""},
        {"Prilaku Rendah":""}]}

Sociability = {"L":[{"Nilai Median":""},
        {"Nilai Tinggi" :""},
        {"Nilai Rendah" :""},
        {"Prilaku Tinggi":""},
        {"Prilaku Rendah":""}],
     "P":[{"Nilai Median":"3.10"},
        {"Nilai Tinggi" :""},
        {"Nilai Rendah" :""},
        {"Prilaku Tinggi":""},
        {"Prilaku Rendah":""}]}

Liveliness = {"L":[{"Nilai Median":""},
        {"Nilai Tinggi" :""},
        {"Nilai Rendah" :""},
        {"Prilaku Tinggi":""},
        {"Prilaku Rendah":""}],
     "P":[{"Nilai Median":"3.10"},
        {"Nilai Tinggi" :""},
        {"Nilai Rendah" :""},
        {"Prilaku Tinggi":""},
        {"Prilaku Rendah":""}]}

Agreeableness = {"L":[{"Nilai Median":""},
        {"Nilai Tinggi" :""},
        {"Nilai Rendah" :""},
        {"Prilaku Tinggi":""},
        {"Prilaku Rendah":""}],
     "P":[{"Nilai Median":"3.10"},
        {"Nilai Tinggi" :""},
        {"Nilai Rendah" :""},
        {"Prilaku Tinggi":""},
        {"Prilaku Rendah":""}]}

Organization = {"L":[{"Nilai Median":""},
        {"Nilai Tinggi" :""},
        {"Nilai Rendah" :""},
        {"Prilaku Tinggi":""},
        {"Prilaku Rendah":""}],
     "P":[{"Nilai Median":"3.10"},
        {"Nilai Tinggi" :""},
        {"Nilai Rendah" :""},
        {"Prilaku Tinggi":""},
        {"Prilaku Rendah":""}]}

Diligence = {"L":[{"Nilai Median":""},
        {"Nilai Tinggi" :""},
        {"Nilai Rendah" :""},
        {"Prilaku Tinggi":""},
        {"Prilaku Rendah":""}],
     "P":[{"Nilai Median":"3.10"},
        {"Nilai Tinggi" :""},
        {"Nilai Rendah" :""},
        {"Prilaku Tinggi":""},
        {"Prilaku Rendah":""}]}

Perfectionism = {"L":[{"Nilai Median":""},
        {"Nilai Tinggi" :""},
        {"Nilai Rendah" :""},
        {"Prilaku Tinggi":""},
        {"Prilaku Rendah":""}],
     "P":[{"Nilai Median":"3.10"},
        {"Nilai Tinggi" :""},
        {"Nilai Rendah" :""},
        {"Prilaku Tinggi":""},
        {"Prilaku Rendah":""}]}

prudence = {"L":[{"Nilai Median":""},
        {"Nilai Tinggi" :""},
        {"Nilai Rendah" :""},
        {"Prilaku Tinggi":""},
        {"Prilaku Rendah":""}],
     "P":[{"Nilai Median":"3.10"},
        {"Nilai Tinggi" :""},
        {"Nilai Rendah" :""},
        {"Prilaku Tinggi":""},
        {"Prilaku Rendah":""}]}

Conscientiouseness = {"L":[{"Nilai Median":""},
        {"Nilai Tinggi" :""},
        {"Nilai Rendah" :""},
        {"Prilaku Tinggi":""},
        {"Prilaku Rendah":""}],
     "P":[{"Nilai Median":"3.10"},
        {"Nilai Tinggi" :""},
        {"Nilai Rendah" :""},
        {"Prilaku Tinggi":""},
        {"Prilaku Rendah":""}]}

Aesthectc_Appreciation = {"L":[{"Nilai Median":""},
        {"Nilai Tinggi" :""},
        {"Nilai Rendah" :""},
        {"Prilaku Tinggi":""},
        {"Prilaku Rendah":""}],
     "P":[{"Nilai Median":"3.10"},
        {"Nilai Tinggi" :""},
        {"Nilai Rendah" :""},
        {"Prilaku Tinggi":""},
        {"Prilaku Rendah":""}]}

b = {"L":[{"Nilai Median":""},
        {"Nilai Tinggi" :""},
        {"Nilai Rendah" :""},
        {"Prilaku Tinggi":""},
        {"Prilaku Rendah":""}],
     "P":[{"Nilai Median":"3.10"},
        {"Nilai Tinggi" :""},
        {"Nilai Rendah" :""},
        {"Prilaku Tinggi":""},
        {"Prilaku Rendah":""}]}

b = {"L":[{"Nilai Median":""},
        {"Nilai Tinggi" :""},
        {"Nilai Rendah" :""},
        {"Prilaku Tinggi":""},
        {"Prilaku Rendah":""}],
     "P":[{"Nilai Median":""},
        {"Nilai Tinggi" :""},
        {"Nilai Rendah" :""},
        {"Prilaku Tinggi":""},
        {"Prilaku Rendah":""}]}

b = {"L":[{"Nilai Median":""},
        {"Nilai Tinggi" :""},
        {"Nilai Rendah" :""},
        {"Prilaku Tinggi":""},
        {"Prilaku Rendah":""}],
     "P":[{"Nilai Median":""},
        {"Nilai Tinggi" :""},
        {"Nilai Rendah" :""},
        {"Prilaku Tinggi":""},
        {"Prilaku Rendah":""}]}

b = {"L":[{"Nilai Median":""},
        {"Nilai Tinggi" :""},
        {"Nilai Rendah" :""},
        {"Prilaku Tinggi":""},
        {"Prilaku Rendah":""}],
     "P":[{"Nilai Median":""},
        {"Nilai Tinggi" :""},
        {"Nilai Rendah" :""},
        {"Prilaku Tinggi":""},
        {"Prilaku Rendah":""}]}

b = {"L":[{"Nilai Median":""},
        {"Nilai Tinggi" :""},
        {"Nilai Rendah" :""},
        {"Prilaku Tinggi":""},
        {"Prilaku Rendah":""}],
     "P":[{"Nilai Median":""},
        {"Nilai Tinggi" :""},
        {"Nilai Rendah" :""},
        {"Prilaku Tinggi":""},
        {"Prilaku Rendah":""}]}

b = {"L":[{"Nilai Median":""},
        {"Nilai Tinggi" :""},
        {"Nilai Rendah" :""},
        {"Prilaku Tinggi":""},
        {"Prilaku Rendah":""}],
     "P":[{"Nilai Median":""},
        {"Nilai Tinggi" :""},
        {"Nilai Rendah" :""},
        {"Prilaku Tinggi":""},
        {"Prilaku Rendah":""}]}

b = {"L":[{"Nilai Median":""},
        {"Nilai Tinggi" :""},
        {"Nilai Rendah" :""},
        {"Prilaku Tinggi":""},
        {"Prilaku Rendah":""}],
     "P":[{"Nilai Median":""},
        {"Nilai Tinggi" :""},
        {"Nilai Rendah" :""},
        {"Prilaku Tinggi":""},
        {"Prilaku Rendah":""}]}

b = {"L":[{"Nilai Median":""},
        {"Nilai Tinggi" :""},
        {"Nilai Rendah" :""},
        {"Prilaku Tinggi":""},
        {"Prilaku Rendah":""}],
     "P":[{"Nilai Median":""},
        {"Nilai Tinggi" :""},
        {"Nilai Rendah" :""},
        {"Prilaku Tinggi":""},
        {"Prilaku Rendah":""}]}

b = {"L":[{"Nilai Median":""},
        {"Nilai Tinggi" :""},
        {"Nilai Rendah" :""},
        {"Prilaku Tinggi":""},
        {"Prilaku Rendah":""}],
     "P":[{"Nilai Median":""},
        {"Nilai Tinggi" :""},
        {"Nilai Rendah" :""},
        {"Prilaku Tinggi":""},
        {"Prilaku Rendah":""}]}

b = {"L":[{"Nilai Median":""},
        {"Nilai Tinggi" :""},
        {"Nilai Rendah" :""},
        {"Prilaku Tinggi":""},
        {"Prilaku Rendah":""}],
     "P":[{"Nilai Median":""},
        {"Nilai Tinggi" :""},
        {"Nilai Rendah" :""},
        {"Prilaku Tinggi":""},
        {"Prilaku Rendah":""}]}

b = {"L":[{"Nilai Median":""},
        {"Nilai Tinggi" :""},
        {"Nilai Rendah" :""},
        {"Prilaku Tinggi":""},
        {"Prilaku Rendah":""}],
     "P":[{"Nilai Median":""},
        {"Nilai Tinggi" :""},
        {"Nilai Rendah" :""},
        {"Prilaku Tinggi":""},
        {"Prilaku Rendah":""}]}

b = {"L":[{"Nilai Median":""},
        {"Nilai Tinggi" :""},
        {"Nilai Rendah" :""},
        {"Prilaku Tinggi":""},
        {"Prilaku Rendah":""}],
     "P":[{"Nilai Median":""},
        {"Nilai Tinggi" :""},
        {"Nilai Rendah" :""},
        {"Prilaku Tinggi":""},
        {"Prilaku Rendah":""}]}

b = {"L":[{"Nilai Median":""},
        {"Nilai Tinggi" :""},
        {"Nilai Rendah" :""},
        {"Prilaku Tinggi":""},
        {"Prilaku Rendah":""}],
     "P":[{"Nilai Median":""},
        {"Nilai Tinggi" :""},
        {"Nilai Rendah" :""},
        {"Prilaku Tinggi":""},
        {"Prilaku Rendah":""}]}

b = {"L":[{"Nilai Median":""},
        {"Nilai Tinggi" :""},
        {"Nilai Rendah" :""},
        {"Prilaku Tinggi":""},
        {"Prilaku Rendah":""}],
     "P":[{"Nilai Median":""},
        {"Nilai Tinggi" :""},
        {"Nilai Rendah" :""},
        {"Prilaku Tinggi":""},
        {"Prilaku Rendah":""}]}

b = {"L":[{"Nilai Median":""},
        {"Nilai Tinggi" :""},
        {"Nilai Rendah" :""},
        {"Prilaku Tinggi":""},
        {"Prilaku Rendah":""}],
     "P":[{"Nilai Median":""},
        {"Nilai Tinggi" :""},
        {"Nilai Rendah" :""},
        {"Prilaku Tinggi":""},
        {"Prilaku Rendah":""}]}

b = {"L":[{"Nilai Median":""},
        {"Nilai Tinggi" :""},
        {"Nilai Rendah" :""},
        {"Prilaku Tinggi":""},
        {"Prilaku Rendah":""}],
     "P":[{"Nilai Median":""},
        {"Nilai Tinggi" :""},
        {"Nilai Rendah" :""},
        {"Prilaku Tinggi":""},
        {"Prilaku Rendah":""}]}

b = {"L":[{"Nilai Median":""},
        {"Nilai Tinggi" :""},
        {"Nilai Rendah" :""},
        {"Prilaku Tinggi":""},
        {"Prilaku Rendah":""}],
     "P":[{"Nilai Median":""},
        {"Nilai Tinggi" :""},
        {"Nilai Rendah" :""},
        {"Prilaku Tinggi":""},
        {"Prilaku Rendah":""}]}

b = {"L":[{"Nilai Median":""},
        {"Nilai Tinggi" :""},
        {"Nilai Rendah" :""},
        {"Prilaku Tinggi":""},
        {"Prilaku Rendah":""}],
     "P":[{"Nilai Median":""},
        {"Nilai Tinggi" :""},
        {"Nilai Rendah" :""},
        {"Prilaku Tinggi":""},
        {"Prilaku Rendah":""}]}

b = {"L":[{"Nilai Median":""},
        {"Nilai Tinggi" :""},
        {"Nilai Rendah" :""},
        {"Prilaku Tinggi":""},
        {"Prilaku Rendah":""}],
     "P":[{"Nilai Median":""},
        {"Nilai Tinggi" :""},
        {"Nilai Rendah" :""},
        {"Prilaku Tinggi":""},
        {"Prilaku Rendah":""}]}

b = {"L":[{"Nilai Median":""},
        {"Nilai Tinggi" :""},
        {"Nilai Rendah" :""},
        {"Prilaku Tinggi":""},
        {"Prilaku Rendah":""}],
     "P":[{"Nilai Median":""},
        {"Nilai Tinggi" :""},
        {"Nilai Rendah" :""},
        {"Prilaku Tinggi":""},
        {"Prilaku Rendah":""}]}

b = {"L":[{"Nilai Median":""},
        {"Nilai Tinggi" :""},
        {"Nilai Rendah" :""},
        {"Prilaku Tinggi":""},
        {"Prilaku Rendah":""}],
     "P":[{"Nilai Median":""},
        {"Nilai Tinggi" :""},
        {"Nilai Rendah" :""},
        {"Prilaku Tinggi":""},
        {"Prilaku Rendah":""}]}

b = {"L":[{"Nilai Median":""},
        {"Nilai Tinggi" :""},
        {"Nilai Rendah" :""},
        {"Prilaku Tinggi":""},
        {"Prilaku Rendah":""}],
     "P":[{"Nilai Median":""},
        {"Nilai Tinggi" :""},
        {"Nilai Rendah" :""},
        {"Prilaku Tinggi":""},
        {"Prilaku Rendah":""}]}

b = {"L":[{"Nilai Median":""},
        {"Nilai Tinggi" :""},
        {"Nilai Rendah" :""},
        {"Prilaku Tinggi":""},
        {"Prilaku Rendah":""}],
     "P":[{"Nilai Median":""},
        {"Nilai Tinggi" :""},
        {"Nilai Rendah" :""},
        {"Prilaku Tinggi":""},
        {"Prilaku Rendah":""}]}
b = {"L":[{"Nilai Median":""},
        {"Nilai Tinggi" :""},
        {"Nilai Rendah" :""},
        {"Prilaku Tinggi":""},
        {"Prilaku Rendah":""}],
     "P":[{"Nilai Median":""},
        {"Nilai Tinggi" :""},
        {"Nilai Rendah" :""},
        {"Prilaku Tinggi":""},
        {"Prilaku Rendah":""}]}

b = {"L":[{"Nilai Median":""},
        {"Nilai Tinggi" :""},
        {"Nilai Rendah" :""},
        {"Prilaku Tinggi":""},
        {"Prilaku Rendah":""}],
     "P":[{"Nilai Median":""},
        {"Nilai Tinggi" :""},
        {"Nilai Rendah" :""},
        {"Prilaku Tinggi":""},
        {"Prilaku Rendah":""}]}

b = {"L":[{"Nilai Median":""},
        {"Nilai Tinggi" :""},
        {"Nilai Rendah" :""},
        {"Prilaku Tinggi":""},
        {"Prilaku Rendah":""}],
     "P":[{"Nilai Median":""},
        {"Nilai Tinggi" :""},
        {"Nilai Rendah" :""},
        {"Prilaku Tinggi":""},
        {"Prilaku Rendah":""}]}

b = {"L":[{"Nilai Median":""},
        {"Nilai Tinggi" :""},
        {"Nilai Rendah" :""},
        {"Prilaku Tinggi":""},
        {"Prilaku Rendah":""}],
     "P":[{"Nilai Median":""},
        {"Nilai Tinggi" :""},
        {"Nilai Rendah" :""},
        {"Prilaku Tinggi":""},
        {"Prilaku Rendah":""}]}

b = {"L":[{"Nilai Median":""},
        {"Nilai Tinggi" :""},
        {"Nilai Rendah" :""},
        {"Prilaku Tinggi":""},
        {"Prilaku Rendah":""}],
     "P":[{"Nilai Median":""},
        {"Nilai Tinggi" :""},
        {"Nilai Rendah" :""},
        {"Prilaku Tinggi":""},
        {"Prilaku Rendah":""}]}
            
             
            
# print (Sincerity["L"]["Nilai Median"])
# print (Sincerity["Nilai Tinggi"])
print (Sincerity["L"][1]["Nilai Tinggi"])