"""Subclass of FrameWarningKey, which is generated by wxFormBuilder."""

import wx
import coreapps.views.FrameKey as FrameKey
import random
import pathlib
# Implementing FrameWarningKey


class authenticationFrameWarningKey(FrameKey.FrameWarningKey):

	def __init__(self, parent):
		FrameKey.FrameWarningKey.__init__(self, parent)
		self.nilai = random.randint(1700, 1900)
		print (self.nilai)
		self.m_staticText6.SetLabel("None")
		self.lisennombor = self.nilai * 4 + 223445435
		self.m_staticText144.SetLabel(str(self.lisennombor))

		# https://www.flaticon.com/authors/pixel-buddha
		# Icon made by [author link] from www.flaticon.com Icon made by [author link] from www.flaticon.com Icon made by [author link] from www.flaticon.com 
		# Icon made by [author link] from www.flaticon.com 

		# Handlers for FrameWarningKey events
		self.pathimage = pathlib.Path.cwd() / "resources/images/symbol/checked.png"
		self.image1 = wx.Image(str(self.pathimage))
		self.re_image1 = self.image1.Rescale(50, 50, quality=wx.IMAGE_QUALITY_NORMAL)
		print (self.pathimage)

		pass

	def m_textCtrl49OnText(self, event):
		# TODO: Implement m_textCtrl49OnText

		pass

	def m_button38OnButtonClick(self, event):
		# TODO: Implement m_button38OnButtonClick

		print ("batal")
		self.Close()
		pass

	def m_button39OnButtonClick(self, event):
		# TODO: Implement m_button39OnButtonClick

		global lisensi
		
		#import file dari folder keygenapps dan tempelfile.py
		from coreapps.models.keygenapps.keygen import Key
		from coreapps.views.tempelfile import TempelFile
		try:
			self.keynumber = self.m_textCtrl49.GetValue()
			print (self.keynumber)
			lisensi = (self.lisennombor - 223445435) / 4
			print (lisensi)
			self.gen = Key(self.keynumber)
	
			print (self.gen.verify(lisensi))
	
			self.verify = self.gen.verify(lisensi)
			# print (self.verify)
			self.yes = TempelFile(self.verify)
			self.yes.compilefile()
			self.m_staticText6.SetLabel("tervalidasi")
			
		except:
			pass
		
		if self.m_staticText6.GetLabel()== "tervalidasi":
			self.Close()
		

		pass

		

root = wx.App()
RunApp = authenticationFrameWarningKey(None)
RunApp.Show()
root.MainLoop()
    
    
