"""Subclass of MyFrame1, which is generated by wxFormBuilder."""

import pathlib

import wx

import coreapps.views.maingui as maingui
from coreapps.views.grafikmatplotlib import PanelObjek

# Implementing MyFrame1
class Hexacofile(maingui.FrameDepan):

	def __init__(self, parent):
		super(Hexacofile, self).__init__(parent)
		self.m_button1.Disable()

		self.grafik_Matplotlib = PanelObjek(self)
		self.GrafikMatplotlib.SetSizer(self.grafik_Matplotlib.sizer90)
		
		
	
		self.GrafikMatplotlib.Update()
		self.GrafikMatplotlib.Refresh()
		self.GrafikMatplotlib.Layout()
		
		self.SetTitle("Aplikasi Binakarir - Hexaco")
		pathimage = pathlib.Path.cwd() / "resources/images/binadata.png"
		self.image1 = wx.Image(str(pathimage))
# 		self.re_image1 = self.image1.Rescale(100,50)
		self.m_bitmap1.SetBitmap(wx.Bitmap(self.image1))

		
# 		self.panel_grafik_matplotlib.SetBackgroundColour(wx.GREEN)
# 		self.panel_grafik_matplotlib.Refresh()
# 		self.panel_grafik_matplotlib.Update()
# 		self.panel_grafik_matplotlib.Layout()
		self.Maximize(maximize=True)
		self.m_simplebook1.SetSelection(0)
		
		
		self.Update()
		self.Refresh()
		self.Layout()

	def m_button1OnButtonClick(self, event):
		self.m_simplebook1.SetSelection(0)
		self.m_button2.Disable()		
		self.m_button3.Enable()
		self.m_button1.Disable()
		
		print ("tes")
		
	def m_button2OnButtonClick(self, event):
		self.getSel = self.m_simplebook1.GetSelection()
		print (self.getSel)
		if self.getSel == 3 :
			self.m_simplebook1.SetSelection(1)
			self.m_button3.Disable()
			print ("dari 60")
		
		elif self.getSel == 2 :
			self.m_simplebook1.SetSelection(1)
			self.m_button3.Disable()
			print ("dari 24")
		
		else :
			self.m_simplebook1.SetSelection(self.getSel - 1)

			if self.getSel - 2 == 2:
				self.m_button3.Disable()
			elif self.getSel - 1 == 0:
				self.m_button2.Disable()		
				self.m_button3.Enable()	
			else :
				self.m_button3.Enable()
				pass
			print ("tes 2")
			
		if self.getSel == 1 :
			self.m_button1.Disable()

		
	def m_button3OnButtonClick(self, event):
		self.getSel = self.m_simplebook1.GetSelection()
		self.m_simplebook1.SetSelection(self.getSel + 1)
		self.m_button1.Enable()

		if self.getSel + 2 == 2:
			self.m_button2.Enable()		
			self.m_button3.Disable()
		else :
			self.m_button3.Enable()
		print ("tes 3")
		
	def m_textCtrl3OnText(self, event):
		self.nama = self.m_textCtrl3.GetValue()
		self.m_textCtrl3.SetValue(self.nama.upper())
		self.m_textCtrl3.SetInsertionPointEnd()
		
	def m_radioBtn1OnRadioButtonSoal24(self, event):
		print ("radio buttton 24")
		self.m_simplebook1.SetSelection(2)
		self.m_panel7.Show()
		self.m_panel8.Hide()
		self.m_button3.Enable()
		self.m_panel9.Hide()
		self.m_panel3.Update()
		self.m_panel3.Refresh()
		self.m_panel3.Layout()
	
	def m_radioBtn2OnRadioButtonSoal60(self, event):
		print ("radio button 60")
		self.m_simplebook1.SetSelection(2)
		self.m_panel7.Hide()
		self.m_panel8.Show()
		self.m_button3.Enable()
		self.m_panel9.Hide()
		self.m_panel3.Update()
		self.m_panel3.Refresh()
		self.m_panel3.Layout()
		
	def m_radioBtn3OnRadioButtonSoal100(self, event):
		print ("radio button 100")
		self.m_simplebook1.SetSelection(2)
		self.m_panel7.Hide()
		self.m_panel8.Hide()
		self.m_panel9.Show()
		self.m_button3.Enable()
		self.m_panel3.Update()
		self.m_panel3.Refresh()
		self.m_panel3.Layout()
	
	def m_button4OnButtonClick24(self, event):
		self.m_radioBtn1OnRadioButtonSoal24(self)

		print ("tes soal item 24")
	
	def m_button5OnButtonClick60(self, event):
		self.m_radioBtn2OnRadioButtonSoal60(self)

		print ("tes soal item 60")
	
	def m_button6OnButtonClick100(self, event):
		self.m_radioBtn3OnRadioButtonSoal100(self)
		print ("tes soal item 100")
		
	def m_button7OnButtonClick(self, event):
		print ("hhjk")
