"""Subclass of MyFrame1, which is generated by wxFormBuilder."""

import pathlib
from coreapps.views.control_text import ControlEntry

import wx

import coreapps.views.maingui as maingui
from coreapps.views.grafikmatplotlib import GrafikDimensi

from coreapps.models.controller import connect_db
from coreapps.views.menubar_tentang import TentangAplikasi
from coreapps.views.maingui import FrameGrafikTerpisah

# Implementing MyFrame1
class Hexacofile(maingui.FrameDepan):

	def __init__(self, parent):
		super(Hexacofile, self).__init__(parent)
# 		Properties Windows Utama
		self.SetTitle("Aplikasi Binakarir - Hexaco")
		self.m_button1.Disable()
		pathimage = pathlib.Path.cwd() / "resources/images/binadata.png"
		self.image1 = wx.Image(str(pathimage))
# 		self.re_image1 = self.image1.Rescale(100,50)
		self.m_bitmap1.SetBitmap(wx.Bitmap(self.image1))

# 		Koneksi Database
		self.path  = pathlib.Path.cwd()/"models/hexacodb"
		self.konek_database = connect_db(self.path)

#  		Design Grafik hasil Hexaco

		self.versi_soal = 24
		self.grafik_matplotlib = GrafikDimensi(self)
		self.grafik_matplotlib.draw()
		self.GrafikMatplotlib.SetSizer(self.grafik_matplotlib.sizer90)
		self.GrafikMatplotlib.Fit()
		
		self.GrafikMatplotlib.Update()
		self.GrafikMatplotlib.Refresh()
		self.GrafikMatplotlib.Layout()

# 		self.grafik_matplotlib1 = GrafikRincianDimensi1(self)
# 		self.grafik_matplotlib1.draw()
# 		self.GrafikMatplotlib1.SetSizer(self.grafik_matplotlib1.sizer98)

# 		self.grafik_matplotlib2 = GrafikRincianDimensi2(self)
# 		self.grafik_matplotlib2.draw()
# 		self.GrafikMatplotlib2.SetSizer(self.grafik_matplotlib2.sizer99)

		
		self.text_entry = ControlEntry(self)
# 		print(self.text_entry.get_input_biodata())
# 		print(self.text_entry.get_input_versi24())
# 		print(self.text_entry.get_input_versi60())
		

		
# 		self.panel_grafik_matplotlib.SetBackgroundColour(wx.GREEN)
# 		self.panel_grafik_matplotlib.Refresh()
# 		self.panel_grafik_matplotlib.Update()
# 		self.panel_grafik_matplotlib.Layout()
		self.Maximize(maximize=True)
		self.m_simplebook1.SetSelection(0)
		
		
		self.Update()
		self.Refresh()
		self.Layout()

	def m_button1OnButtonClick(self, event):
		self.m_simplebook1.SetSelection(0)
		self.m_button2.Disable()		
		self.m_button3.Enable()
		self.m_button1.Disable()
		
		print ("tes")
		
	def m_button2OnButtonClick(self, event):
		self.getSel = self.m_simplebook1.GetSelection()
		print (self.getSel)
		
		self.m_simplebook1.SetSelection(self.getSel - 1)
		self.getSel = self.m_simplebook1.GetSelection()
		print (self.getSel)
		
		if self.getSel == 1:
			self.m_button3.Disable()
			
		elif self.getSel  == 0:
			self.m_button1.Disable()
			self.m_button2.Disable()		
			self.m_button3.Enable()	
			
		else :
			self.m_button3.Enable()
			pass
		print ("tes 2")
		
		
	def m_button3OnButtonClick(self, event):

		try:
			self.getSel = self.m_simplebook1.GetSelection()
			print (self.getSel)
			self.m_simplebook1.SetSelection(self.getSel + 1)
			self.getSel = self.m_simplebook1.GetSelection()
			print (self.getSel)
	
			self.m_button1.Enable()
	
			if self.getSel == 1:
				self.m_button2.Enable()		
				self.m_button3.Disable()
			else :
				self.m_button3.Enable()
			print ("tes 3")

		except :
			self.m_button3.Disable()# 		print(self.text_entry.get_input_versi24())
# 		print(self.text_entry.get_input_versi60())
# 		print(self.text_entry.get_input_versi100())


	def m_textCtrl3OnText(self, event):
		self.nama = self.m_textCtrl3.GetValue()
		self.m_textCtrl3.SetValue(self.nama.upper())
		self.m_textCtrl3.SetInsertionPointEnd()
		
	def m_radioBtn1OnRadioButtonSoal24(self, event):
		print ("radio buttton 24")
		self.m_simplebook1.SetSelection(2)
		self.m_panel7.Show()
		self.m_panel8.Hide()
		self.m_button3.Enable()
		self.m_panel9.Hide()
		self.m_panel3.Update()
		self.m_panel3.Refresh()
		self.m_panel3.Layout()
	
	def m_radioBtn2OnRadioButtonSoal60(self, event):
		print ("radio button 60")
		self.m_simplebook1.SetSelection(2)
		self.m_panel7.Hide()
		self.m_panel8.Show()
		self.m_button3.Enable()
		self.m_panel9.Hide()
		self.m_panel3.Update()
		self.m_panel3.Refresh()
		self.m_panel3.Layout()
		
	def m_radioBtn3OnRadioButtonSoal100(self, event):
		print ("radio button 100")
		self.m_simplebook1.SetSelection(2)
		self.m_panel7.Hide()
		self.m_panel8.Hide()
		self.m_panel9.Show()
		self.m_button3.Enable()
		self.m_panel3.Update()
		self.m_panel3.Refresh()
		self.m_panel3.Layout()
	
	def m_button4OnButtonClick24(self, event):
		self.m_radioBtn1OnRadioButtonSoal24(self)

		print ("tes soal item 24")
	
	def m_button5OnButtonClick60(self, event):
		self.m_radioBtn2OnRadioButtonSoal60(self)

		print ("tes soal item 60")
	
	def m_button6OnButtonClick100(self, event):
		self.m_radioBtn3OnRadioButtonSoal100(self)
		print ("tes soal item 100")
		
	def m_button7OnButtonClick(self, event):
		print ("hhjk")
		
		
	def m_menuItem1OnMenuSelection(self,event):
		self.Close()
		print ("Aplikasi ditutup")
		
	def m_button_cOnButtonClick(self, event):
		print ("tes over here 'c'")
		pass
	
	def m_button_aOnButtonClick(self, event):
		print ("tes over here 'a'")
		pass
	
	def m_button_emOnButtonClick(self, event):
		print ("tes over here 'em'")
		pass
	
	def m_button_hOnButtonClick(self, event):
		print ("tes over here 'h'")
		pass
	
	def m_button_exOnButtonClick(self, event):
		print ("tes over here ' ex '")
		pass
	
	def m_button_oOnButtonClick(self, event):
		print ("print over here 'o'")
		
# 		from coreapps.views.grafikmatplotlib import GrafikO
# 		self.tampil_grafik_o = GrafikO(self)
		
		self.buka_grafik = FrameGrafikTerpisah(self)
		self.buka_grafik.Show()
		pass
	
	def m_menuItem2OnMenuSelection(self, event):
		self.buka = TentangAplikasi(self)
		self.buka.Show()
		
	

		
	
